Test terraform cdktf github action

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -28,52 +28,60 @@ jobs:
         run: |
           cd main
           npm install
-          npm install --global cdktf-cli@latest
+
+      - name: Generate module and provider bindings
+        run: npx cdktf-cli get
 
       - name: Local Test
         id: local-test
         run: |
           cd main
           npm test
-
-      - name: CDKTF Synth
-        id: synth
-        run: |
-          cd main
-          cdktf synth -o ../
-
-      - name: Terraform Init
-        run: |
-          cd stacks/main
-          terraform init
-
-      - name: Terraform Plan
-        id: plan
-        run: |
-          cd stacks/main
-          echo 'PLAN_OUTPUT<<EOF' >> $GITHUB_ENV
-          terraform plan -no-color >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
-
-      - name: Create comment
-        uses: peter-evans/create-or-update-comment@v2
+          
+      - name: Test the synth
+        uses: hashicorp/terraform-cdk-action@v0.1.0
         with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            #### Terraform Plan 📖`${{ steps.plan.outcome }}`
+          stackName: main
+          mode: plan-only
 
-            <details><summary>Show Plan</summary>
-
-            ```${{ env.PLAN_OUTPUT }}
-            ```
-
-            </details>
-
-            **Pull Request by: @${{ github.actor }}**
-
-      - name: CDKTF Plan Status
-        if: steps.plan.outcome == 'failure' || steps.local-test.outcome == 'failure'
-        run: exit 1
+#      - name: CDKTF Synth
+#        id: synth
+#        run: |
+#          cd main
+#          cdktf synth -o ../
+#
+#      - name: Terraform Init
+#        run: |
+#          cd stacks/main
+#          terraform init
+#
+#      - name: Terraform Plan
+#        id: plan
+#        run: |
+#          cd stacks/main
+#          echo 'PLAN_OUTPUT<<EOF' >> $GITHUB_ENV
+#          terraform plan -no-color >> $GITHUB_ENV
+#          echo 'EOF' >> $GITHUB_ENV
+#
+#      - name: Create comment
+#        uses: peter-evans/create-or-update-comment@v2
+#        with:
+#          issue-number: ${{ github.event.pull_request.number }}
+#          body: |
+#            #### Terraform Plan 📖`${{ steps.plan.outcome }}`
+#
+#            <details><summary>Show Plan</summary>
+#
+#            ```${{ env.PLAN_OUTPUT }}
+#            ```
+#
+#            </details>
+#
+#            **Pull Request by: @${{ github.actor }}**
+#
+#      - name: CDKTF Plan Status
+#        if: steps.plan.outcome == 'failure' || steps.local-test.outcome == 'failure'
+#        run: exit 1
 
       - run: |
           echo The Terraform build has been successfully validated
